### ISSUE TITLE
MapBoxOfflineTileProvider layer flicker

### ISSUE THREAD

**Issue by ramonpoca** [cocoahero/android-gmaps-addons#2]
Hi there,

We are using MapBoxOfflineTileProvider with a custom, large map. When zooming the map flickers a lot until it redraws. 
From http://stackoverflow.com/questions/14409813/how-to-update-tileoverlay-without-a-flicker I presume this is not an artifact of MapBoxOfflineTileProvider, rather a google maps problem.

Do you know of any way to alleviate this?

**Comment by cocoahero** [comment]
I have too seen this behavior, and it is most definitely an issue within the Google Maps SDK, not with this library. There is actually an SDK issue for this very bug here: https://code.google.com/p/gmaps-api-issues/issues/detail?id=4649

Sorry for the extremely delayed response! =(
