### ISSUE TITLE
How to set the map 'really' offline? 

### ISSUE THREAD

**Issue by Humbertda** [cocoahero/android-gmaps-addons#3]
Hi, 

First of all, thank you for your awesome add-on! very simple to use and working perfectly !

But, "how to have the map without google"?
I mean when I am totally offline (disable data) i can't load anything. And when I turn on datas for 2 secondes, i can load Google Map, here I have markers and World Map.

Then i disable again datas, google can't load anymore tiles. And I am still able to load the MBtiles witch I have created offline !

How could I force MBtiles to load without datas? 

Hope you could understand my question!

Thank you again!

Regards

**Comment by cocoahero** [comment]
This may be a symptom of the Google Play Services library requiring a "phone home" in order to authorize. However, something you can try is to set the GoogleMap instance's map type to MAP_TYPE_NONE. This will disable the Google base layer completely, but I am not sure if it will allow you to see your MBTiles completely offline.

Sorry for the delayed response!

**Comment by Humbertda** [comment]
No problem! 

I tried to change map type to MAP_TYPE_NONE and it worked totally offline!
First time I launched the app without any networks, my map was loaded with all markers and polylines !

It could be very helpful for other people who have this issue in "read-me" ! 

Thanks a lot for your work, this add-on should be more famous ! :+1: 

Regards,
Dany

**Comment by cocoahero** [comment]
Glad it worked. I'll add that to the README.

Thanks for the kind words. =)

**Comment by hallahan** [comment]
I'm finding that

```
mMap.setMapType(GoogleMap.MAP_TYPE_NONE);
```

actually does not work. If you install the app, gmaps does indeed need to "phone home" at least once, even for offline maps. It may seem to work, but if you try manually deleting the app and then deploying it again with all internet off, gmaps will not work.

Any ideas?
